-- vim.cmd('set background=light')
vim.cmd('colorscheme vim')
vim.api.nvim_set_hl(0, "SignColumn", { bg = "None" })
vim.api.nvim_set_hl(0, 'NormalFloat', { link = "Normal" })
vim.api.nvim_set_hl(0, 'Pmenu', { link = "Normal" })
