-- require("hlchunk").setup({
--         chunk = {
--                 enable = true,
--                 use_treesitter = true,
--                 style = {
--                         { fg = "#806d9c" },
--                         -- { fg = "#501f8f" },
--                         { fg = "#c21f30" }, -- this fg is used to highlight wrong chunk
--                 },
--         },
--         indent = {
--                 enable = true,
--                 use_treesitter = true,
--                 chars = { "│" }, -- more code can be found in https://unicodeplus.com/
--                 -- style = {
--                 --         "#8B00FF",
--                 -- },
--         },
--         line_num = {
--                 enable = true,
--                 use_treesitter = false,
--                 style = "#806d9c",
--                 -- style = "#501f8f",
--         },
--         blank = {
--                 enable = false,
--         }
-- })
